package fqf.qua_mario.characters;

public enum CharaStat {
	WALK_ACCEL(0.045),
	WALK_STANDSTILL_ACCEL(0.125),
	WALK_STANDSTILL_THRESHOLD(0.12),
	WALK_SPEED(0.275),
	WALK_REDIRECTION(0),
	OVERWALK_ACCEL(0.02),

	IDLE_DEACCEL(0.075),

	BACKPEDAL_ACCEL(0.055),
	BACKPEDAL_SPEED(-0.225),
	BACKPEDAL_REDIRECTION(0),
	OVERBACKPEDAL_ACCEL(0.04),

	SKID_THRESHOLD(0.285),
	SKID_FACTOR(0),

	RUN_ACCEL(0.0185),
	RUN_SPEED(0.5),
	RUN_REDIRECTION(2.75),
	OVERRUN_ACCEL(0.0175),

	P_SPEED(0.525),
	P_SPEED_REDIRECTION(3.4),

	STRAFE_ACCEL(0.065),
	STRAFE_SPEED(0.275),

	DRIFT_FORWARD_ACCEL(0),
	DRIFT_FORWARD_SPEED(0),
	DRIFT_SIDE_ACCEL(0),
	DRIFT_SIDE_SPEED(0),
	DRIFT_BACKWARD_ACCEL(0),
	DRIFT_BACKWARD_SPEED(0),
	DRIFT_REDIRECTION(0),

	JUMP_VELOCITY(0),
	JUMP_CAP(0),
	GRAVITY(0),

	SIDEFLIP_VELOCITY(0),
	SIDEFLIP_CAP(0),
	SIDEFLIP_THRESHOLD(0),
	SIDEFLIP_BACKWARD_SPEED(0),

	CROUCH_JUMP_VELOCITY(0),
	CROUCH_JUMP_CAP(0),

	DOUBLE_JUMP_VELOCITY(0),
	DOUBLE_JUMP_CAP(0),

	TRIPLE_JUMP_VELOCITY(0),
	TRIPLE_JUMP_CAP(0),

	LONG_JUMP_VELOCITY(0),
	LONG_JUMP_CAP(0),
	LONG_JUMP_SPEED_FACTOR(0),
	LONG_JUMP_SPEED_ADDEND(0),
	LONG_JUMP_SPEED_CAP(0),

	ZERO(0);

	private final double DEFAULT_VALUE;
	CharaStat(double defaultValue) {
		this.DEFAULT_VALUE = defaultValue;
	}
	public double getDefaultValue() {
		return DEFAULT_VALUE;
	}
}
